receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"   # Export endpoint for Prometheus to scrape

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
